export { Home } from "./Home/Home";
export { Products } from "./Products/Products";
export { ProductDetail } from "./ProductDetail";
export { Cart } from "./Cart/Cart";
export { Login } from "./Login";
export { Register } from "./Register";
export { Order } from "./Order/Order";
export { Dashboard } from "./Dashboard/Dashboard";
export { PageNotFound } from "./PageNotFound";
